baseURL = "https://cranky-curie-31d16d.netlify.com/"
languageCode = "en-us"
title = "Test Hugo"
theme = "jeffprod"

[permalinks]
	post = "/:year/:filename"

[taxonomies]
	tag = "tags"
	acrhive = "archives"
